import React, { useState } from 'react';
import { TYPOGRAPHY, CARDS, BUTTONS, MODALS } from '../utils/typography';

interface LegalDisclaimerProps {
  /** Display mode: 'inline' for embedded view, 'modal' for popup, 'compact' for footer */
  variant?: 'inline' | 'modal' | 'compact';
  /** Callback when modal is closed (only for modal variant) */
  onClose?: () => void;
  /** Show only if not previously acknowledged (uses localStorage) */
  requireAcknowledgment?: boolean;
  /** Storage key for acknowledgment (defaults to 'forgecomply_disclaimer_ack') */
  storageKey?: string;
}

const DISCLAIMER_VERSION = '1.0.0';

export function LegalDisclaimer({
  variant = 'inline',
  onClose,
  requireAcknowledgment = false,
  storageKey = 'forgecomply_disclaimer_ack',
}: LegalDisclaimerProps) {
  const [acknowledged, setAcknowledged] = useState(() => {
    if (!requireAcknowledgment) return true;
    const stored = localStorage.getItem(storageKey);
    return stored === DISCLAIMER_VERSION;
  });

  const handleAcknowledge = () => {
    localStorage.setItem(storageKey, DISCLAIMER_VERSION);
    setAcknowledged(true);
    onClose?.();
  };

  // If acknowledged and we're in modal mode, don't render
  if (acknowledged && variant === 'modal' && requireAcknowledgment) {
    return null;
  }

  const disclaimerContent = (
    <>
      <section className="mb-4">
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>No Legal or Compliance Advice</h3>
        <p className={TYPOGRAPHY.body}>
          ForgeComply 360 is a compliance management tool designed to help organizations track and manage
          their compliance activities. This software does <strong>not</strong> provide legal, regulatory,
          or professional compliance advice. The information, recommendations, and outputs generated by
          this tool should not be construed as legal counsel or a substitute for professional advice
          from qualified compliance officers, attorneys, or regulatory experts.
        </p>
      </section>

      <section className="mb-4">
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>No Guarantee of Compliance</h3>
        <p className={TYPOGRAPHY.body}>
          Use of ForgeComply 360 does not guarantee compliance with any federal, state, or industry
          regulatory framework, including but not limited to FedRAMP, NIST, HIPAA, SOC 2, ISO 27001,
          PCI-DSS, or any other compliance standard. Achieving and maintaining compliance requires
          ongoing assessment, implementation of appropriate controls, and validation by qualified
          assessors. This tool is an aid to your compliance program, not a replacement for proper
          compliance processes.
        </p>
      </section>

      <section className="mb-4">
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>AI-Generated Content</h3>
        <p className={TYPOGRAPHY.body}>
          Certain features of this application utilize artificial intelligence (AI) to generate
          documentation, policy language, control implementations, and other content. AI-generated
          content is provided as a starting point only and <strong>must be reviewed, validated, and
          approved</strong> by qualified personnel before use. The accuracy, completeness, and
          appropriateness of AI-generated content cannot be guaranteed. Organizations are solely
          responsible for verifying that all documentation meets their specific requirements and
          applicable regulatory standards.
        </p>
      </section>

      <section className="mb-4">
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>Limitation of Liability</h3>
        <p className={TYPOGRAPHY.body}>
          To the maximum extent permitted by applicable law, in no event shall the developers,
          operators, or licensors of ForgeComply 360 be liable for any indirect, incidental,
          special, consequential, or punitive damages, including without limitation, loss of
          profits, data, use, goodwill, or other intangible losses, resulting from (i) your
          access to or use of or inability to access or use the service; (ii) any conduct or
          content of any third party on the service; (iii) any content obtained from the service;
          or (iv) unauthorized access, use, or alteration of your transmissions or content.
        </p>
      </section>

      <section className="mb-4">
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>No Warranty</h3>
        <p className={TYPOGRAPHY.body}>
          This software is provided "as is" and "as available" without warranty of any kind,
          either express or implied, including but not limited to the implied warranties of
          merchantability, fitness for a particular purpose, and non-infringement. The entire
          risk as to the quality and performance of the software is with you.
        </p>
      </section>

      <section className="mb-4">
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>Data Security</h3>
        <p className={TYPOGRAPHY.body}>
          While we implement security measures to protect your data, no method of transmission
          over the Internet or electronic storage is 100% secure. You are responsible for
          maintaining the confidentiality of your account credentials and for restricting
          access to your systems. You agree to accept responsibility for all activities that
          occur under your account.
        </p>
      </section>

      <section>
        <h3 className={`${TYPOGRAPHY.subsectionTitle} mb-2`}>Professional Consultation</h3>
        <p className={TYPOGRAPHY.body}>
          We strongly recommend consulting with qualified legal, compliance, and security
          professionals before making compliance decisions. This tool should be used as part
          of a comprehensive compliance program that includes human oversight, professional
          guidance, and regular assessments by qualified third-party assessors.
        </p>
      </section>
    </>
  );

  // Compact variant (for footer)
  if (variant === 'compact') {
    return (
      <div className="text-center py-4 border-t border-gray-200 dark:border-gray-700">
        <p className={TYPOGRAPHY.bodySmallMuted}>
          ForgeComply 360 is a compliance management tool and does not provide legal advice.
          Use of this software does not guarantee regulatory compliance.{' '}
          <button
            onClick={() => window.dispatchEvent(new CustomEvent('show-full-disclaimer'))}
            className={TYPOGRAPHY.link}
          >
            View Full Disclaimer
          </button>
        </p>
      </div>
    );
  }

  // Modal variant
  if (variant === 'modal') {
    return (
      <div className={MODALS.backdrop}>
        <div className={MODALS.containerWide}>
          <div className={MODALS.header}>
            <h2 className={TYPOGRAPHY.modalTitle}>Legal Disclaimer</h2>
            {!requireAcknowledgment && (
              <button onClick={onClose} className={MODALS.closeButton}>
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}
          </div>
          <div className={`${MODALS.body} max-h-[60vh] overflow-y-auto`}>
            {disclaimerContent}
          </div>
          <div className={MODALS.footer}>
            {requireAcknowledgment ? (
              <button onClick={handleAcknowledge} className={BUTTONS.primary}>
                I Understand and Acknowledge
              </button>
            ) : (
              <button onClick={onClose} className={BUTTONS.secondary}>
                Close
              </button>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Inline variant (default)
  return (
    <div className={`${CARDS.elevated} p-6`}>
      <div className="flex items-center gap-3 mb-4">
        <div className="p-2 bg-amber-100 rounded-lg">
          <svg className="w-6 h-6 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        </div>
        <div>
          <h2 className={TYPOGRAPHY.sectionTitle}>Legal Disclaimer</h2>
          <p className={TYPOGRAPHY.bodySmallMuted}>Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
      {disclaimerContent}
    </div>
  );
}

// Hook to show the disclaimer modal programmatically
export function useDisclaimerModal() {
  const [showModal, setShowModal] = useState(false);

  React.useEffect(() => {
    const handleShowDisclaimer = () => setShowModal(true);
    window.addEventListener('show-full-disclaimer', handleShowDisclaimer);
    return () => window.removeEventListener('show-full-disclaimer', handleShowDisclaimer);
  }, []);

  return {
    showModal,
    openModal: () => setShowModal(true),
    closeModal: () => setShowModal(false),
  };
}
