// exportHelpers.ts — Pure browser-based export utilities (no external libraries)

/**
 * Trigger a file download in the browser via an invisible anchor element.
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Escape HTML special characters for safe embedding inside Word-HTML documents.
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Escape a value for safe embedding in a CSV cell.
 */
function csvCell(value: string | number | undefined | null): string {
  const str = String(value ?? '');
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// ---------------------------------------------------------------------------
// 1. Export as DOCX (HTML-based Word document)
// ---------------------------------------------------------------------------

/**
 * Creates an HTML document with Microsoft Office XML namespace declarations
 * so that Word opens it natively with proper formatting.
 * Saved with a .doc extension (Word opens these seamlessly).
 */
export async function exportAsDocx(title: string, content: string): Promise<void> {
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)}</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotOptimizeForBrowser/>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    @page {
      size: 8.5in 11in;
      margin: 1in;
    }
    body {
      font-family: 'Calibri', 'Segoe UI', Arial, sans-serif;
      font-size: 11pt;
      color: #1a1a1a;
      line-height: 1.5;
    }
    h1 {
      font-size: 22pt;
      color: #1e3a5f;
      border-bottom: 2px solid #1e3a5f;
      padding-bottom: 6pt;
      margin-bottom: 12pt;
    }
    h2 {
      font-size: 16pt;
      color: #2a5a8a;
      margin-top: 18pt;
      margin-bottom: 8pt;
    }
    h3 {
      font-size: 13pt;
      color: #3a6a9a;
      margin-top: 12pt;
      margin-bottom: 6pt;
    }
    table {
      border-collapse: collapse;
      width: 100%;
      margin: 10pt 0;
    }
    th, td {
      border: 1px solid #b0b0b0;
      padding: 6pt 8pt;
      text-align: left;
      vertical-align: top;
      font-size: 10pt;
    }
    th {
      background-color: #1e3a5f;
      color: #ffffff;
      font-weight: bold;
    }
    tr:nth-child(even) td {
      background-color: #f4f7fb;
    }
    .meta {
      color: #666;
      font-size: 10pt;
      margin-bottom: 16pt;
    }
    .page-break {
      page-break-before: always;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p class="meta">Generated on ${escapeHtml(now)} by ForgeComply 360</p>
  ${content}
</body>
</html>`.trim();

  const blob = new Blob([html], { type: 'application/msword' });
  const safeName = title.replace(/[^a-zA-Z0-9_\- ]/g, '').replace(/\s+/g, '_');
  downloadBlob(blob, `${safeName}.doc`);
}

// ---------------------------------------------------------------------------
// 2. Export SSP Package as a formatted Word-compatible document
// ---------------------------------------------------------------------------

export async function exportSSPPackageDoc(
  systemName: string,
  frameworkName: string,
  implementations: any[],
  orgName: string,
): Promise<void> {
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // --- Title Page ---
  let content = `
  <div style="text-align:center; padding-top:120pt; padding-bottom:120pt;">
    <h1 style="font-size:28pt; border:none; text-align:center;">${escapeHtml(frameworkName)}</h1>
    <h2 style="font-size:20pt; color:#333; text-align:center;">System Security Plan</h2>
    <p style="font-size:14pt; color:#555; margin-top:24pt;">${escapeHtml(systemName)}</p>
    <p style="font-size:12pt; color:#777; margin-top:12pt;">${escapeHtml(orgName)}</p>
    <p style="font-size:11pt; color:#999; margin-top:24pt;">${escapeHtml(now)}</p>
    <p style="font-size:9pt; color:#aaa; margin-top:36pt;">Generated by ForgeComply 360</p>
  </div>
  <div class="page-break"></div>
  `;

  // --- Table of Contents ---
  content += `
  <h2>Table of Contents</h2>
  <ol>
    <li>Introduction</li>
    <li>System Overview</li>
    <li>Control Implementation Summary</li>
    <li>Control Implementation Details</li>
  </ol>
  <div class="page-break"></div>
  `;

  // --- Section 1: Introduction ---
  content += `
  <h2>1. Introduction</h2>
  <p>This System Security Plan (SSP) documents the security controls implemented for
  <strong>${escapeHtml(systemName)}</strong> in accordance with the
  <strong>${escapeHtml(frameworkName)}</strong> framework. It provides a comprehensive
  record of the security posture, control implementation status, and responsible parties
  for the organization <strong>${escapeHtml(orgName)}</strong>.</p>
  `;

  // --- Section 2: System Overview ---
  const totalControls = implementations.length;
  const statusCounts: Record<string, number> = {};
  for (const impl of implementations) {
    const st = impl.status || 'not_implemented';
    statusCounts[st] = (statusCounts[st] || 0) + 1;
  }

  content += `
  <h2>2. System Overview</h2>
  <table>
    <tr><th>Attribute</th><th>Value</th></tr>
    <tr><td>System Name</td><td>${escapeHtml(systemName)}</td></tr>
    <tr><td>Framework</td><td>${escapeHtml(frameworkName)}</td></tr>
    <tr><td>Organization</td><td>${escapeHtml(orgName)}</td></tr>
    <tr><td>Total Controls</td><td>${totalControls}</td></tr>
    <tr><td>Date Generated</td><td>${escapeHtml(now)}</td></tr>
  </table>
  `;

  // --- Section 3: Summary ---
  content += `
  <h2>3. Control Implementation Summary</h2>
  <table>
    <tr><th>Status</th><th>Count</th><th>Percentage</th></tr>
  `;
  const statusLabels: Record<string, string> = {
    implemented: 'Implemented',
    partially_implemented: 'Partially Implemented',
    planned: 'Planned',
    not_implemented: 'Not Implemented',
    not_applicable: 'Not Applicable',
  };
  for (const [key, label] of Object.entries(statusLabels)) {
    const count = statusCounts[key] || 0;
    const pct = totalControls > 0 ? ((count / totalControls) * 100).toFixed(1) : '0.0';
    content += `<tr><td>${label}</td><td>${count}</td><td>${pct}%</td></tr>`;
  }
  content += `</table><div class="page-break"></div>`;

  // --- Section 4: Control Details ---
  content += `<h2>4. Control Implementation Details</h2>`;

  for (const impl of implementations) {
    const controlId = impl.control_id || impl.controlId || 'N/A';
    const title = impl.title || impl.control_title || '';
    const status = statusLabels[impl.status] || impl.status || 'Not Implemented';
    const role = impl.responsible_role || impl.responsibleRole || 'Unassigned';
    const narrative = impl.narrative || impl.implementation_narrative || '';

    content += `
    <h3>${escapeHtml(controlId)}${title ? ' — ' + escapeHtml(title) : ''}</h3>
    <table>
      <tr><th style="width:160px;">Control ID</th><td>${escapeHtml(controlId)}</td></tr>
      ${title ? `<tr><th>Title</th><td>${escapeHtml(title)}</td></tr>` : ''}
      <tr><th>Status</th><td>${escapeHtml(status)}</td></tr>
      <tr><th>Responsible Role</th><td>${escapeHtml(role)}</td></tr>
      <tr><th>Implementation Narrative</th><td>${narrative ? escapeHtml(narrative) : '<em>No narrative provided</em>'}</td></tr>
    </table>
    `;
  }

  const docTitle = `SSP - ${systemName} - ${frameworkName}`;
  await exportAsDocx(docTitle, content);
}

// ---------------------------------------------------------------------------
// 2b. Export full SSP with authored sections as a formatted Word doc
// ---------------------------------------------------------------------------

const SSP_SECTION_LABELS_EXPORT: Record<string, string> = {
  system_info: 'System Information', authorization_boundary: 'Authorization Boundary',
  data_flow: 'Data Flow', network_architecture: 'Network Architecture',
  system_interconnections: 'System Interconnections', personnel: 'Personnel & Roles',
  control_implementations: 'Control Implementations', contingency_plan: 'Contingency Plan Summary',
  incident_response: 'Incident Response Summary', continuous_monitoring: 'Continuous Monitoring Strategy',
};

const SSP_SECTION_ORDER = ['system_info','authorization_boundary','data_flow','network_architecture','system_interconnections','personnel','control_implementations','contingency_plan','incident_response','continuous_monitoring'];

export async function exportFullSSPDoc(
  systemName: string,
  frameworkName: string,
  orgName: string,
  sections: Record<string, { content: string; status: string }>,
  implementations?: any[],
): Promise<void> {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  let content = `
  <div style="text-align:center; padding-top:120pt; padding-bottom:120pt;">
    <h1 style="font-size:28pt; border:none; text-align:center;">${escapeHtml(frameworkName)}</h1>
    <h2 style="font-size:20pt; color:#333; text-align:center;">System Security Plan</h2>
    <p style="font-size:14pt; color:#555; margin-top:24pt;">${escapeHtml(systemName)}</p>
    <p style="font-size:12pt; color:#777; margin-top:12pt;">${escapeHtml(orgName)}</p>
    <p style="font-size:11pt; color:#999; margin-top:24pt;">${escapeHtml(now)}</p>
    <p style="font-size:9pt; color:#aaa; margin-top:36pt;">Generated by ForgeComply 360</p>
  </div>
  <div class="page-break"></div>
  `;

  // Table of Contents
  content += `<h2>Table of Contents</h2><ol>`;
  SSP_SECTION_ORDER.forEach((key, i) => {
    content += `<li>${SSP_SECTION_LABELS_EXPORT[key] || key}</li>`;
  });
  if (implementations?.length) content += `<li>Detailed Control Implementations</li>`;
  content += `</ol><div class="page-break"></div>`;

  // Sections
  SSP_SECTION_ORDER.forEach((key, i) => {
    const label = SSP_SECTION_LABELS_EXPORT[key] || key;
    const sec = sections[key];
    const text = sec?.content?.trim() || '(Section not yet completed)';
    content += `<h2>${i + 1}. ${escapeHtml(label)}</h2>`;
    // Convert newlines to paragraphs
    text.split(/\n\n+/).forEach(para => {
      content += `<p>${escapeHtml(para.trim()).replace(/\n/g, '<br/>')}</p>`;
    });
    content += `<div class="page-break"></div>`;
  });

  // Detailed control implementations table (if provided)
  if (implementations?.length) {
    const statusLabels: Record<string, string> = {
      implemented: 'Implemented', partially_implemented: 'Partially Implemented',
      planned: 'Planned', not_implemented: 'Not Implemented', not_applicable: 'Not Applicable',
    };
    content += `<h2>${SSP_SECTION_ORDER.length + 1}. Detailed Control Implementations</h2>`;
    for (const impl of implementations) {
      const controlId = impl.control_id || 'N/A';
      const title = impl.title || impl.control_title || '';
      const status = statusLabels[impl.status] || impl.status || 'Not Implemented';
      const narrative = impl.narrative || impl.implementation_narrative || '';
      content += `
      <h3>${escapeHtml(controlId)}${title ? ' — ' + escapeHtml(title) : ''}</h3>
      <table>
        <tr><th style="width:160px;">Status</th><td>${escapeHtml(status)}</td></tr>
        <tr><th>Responsible Role</th><td>${escapeHtml(impl.responsible_role || 'Unassigned')}</td></tr>
        <tr><th>Narrative</th><td>${narrative ? escapeHtml(narrative) : '<em>Pending</em>'}</td></tr>
      </table>`;
    }
  }

  await exportAsDocx(`SSP - ${systemName} - ${frameworkName}`, content);
}

export async function exportSSPSectionDoc(
  sectionLabel: string,
  sectionContent: string,
  systemName: string,
  frameworkName: string,
  orgName: string,
): Promise<void> {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  let content = `
  <h1>System Security Plan — ${escapeHtml(sectionLabel)}</h1>
  <table>
    <tr><th>System</th><td>${escapeHtml(systemName)}</td></tr>
    <tr><th>Framework</th><td>${escapeHtml(frameworkName)}</td></tr>
    <tr><th>Organization</th><td>${escapeHtml(orgName)}</td></tr>
    <tr><th>Date</th><td>${escapeHtml(now)}</td></tr>
  </table>
  <h2>${escapeHtml(sectionLabel)}</h2>`;
  sectionContent.split(/\n\n+/).forEach(para => {
    content += `<p>${escapeHtml(para.trim()).replace(/\n/g, '<br/>')}</p>`;
  });
  await exportAsDocx(`SSP Section - ${sectionLabel} - ${systemName}`, content);
}

// ---------------------------------------------------------------------------
// 3. Export controls as CSV
// ---------------------------------------------------------------------------

export function exportControlsCSV(
  controls: any[],
  implementations: Record<string, any>,
  frameworkName: string,
): void {
  const headers = [
    'Control ID',
    'Title',
    'Family',
    'Status',
    'Responsible Role',
    'Implementation Description',
    'AI Narrative',
  ];

  const rows: string[] = [headers.map(csvCell).join(',')];

  for (const ctrl of controls) {
    const id = ctrl.control_id || ctrl.controlId || ctrl.id || '';
    const impl = implementations[id] || {};
    const row = [
      csvCell(id),
      csvCell(ctrl.title || ''),
      csvCell(ctrl.family || ''),
      csvCell(impl.status || 'not_implemented'),
      csvCell(impl.responsible_role || impl.responsibleRole || ''),
      csvCell(impl.description || impl.implementation_description || ''),
      csvCell(impl.ai_narrative || impl.narrative || ''),
    ];
    rows.push(row.join(','));
  }

  const csv = rows.join('\r\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const safeName = frameworkName.replace(/[^a-zA-Z0-9_\- ]/g, '').replace(/\s+/g, '_');
  downloadBlob(blob, `${safeName}_Controls_Export.csv`);
}

// ---------------------------------------------------------------------------
// 4. Export audit logs as CSV
// ---------------------------------------------------------------------------

export function exportAuditLogCSV(logs: any[]): void {
  const headers = [
    'Timestamp',
    'User',
    'Email',
    'Action',
    'Resource Type',
    'Resource ID',
    'Details',
    'IP Address',
  ];

  const rows: string[] = [headers.map(csvCell).join(',')];

  for (const log of logs) {
    let details = '';
    try {
      const obj = typeof log.details === 'string' ? JSON.parse(log.details) : log.details;
      details = JSON.stringify(obj);
    } catch {
      details = log.details || '';
    }
    const row = [
      csvCell(log.created_at || ''),
      csvCell(log.user_name || 'System'),
      csvCell(log.user_email || ''),
      csvCell(log.action || ''),
      csvCell(log.resource_type || ''),
      csvCell(log.resource_id || ''),
      csvCell(details),
      csvCell(log.ip_address || ''),
    ];
    rows.push(row.join(','));
  }

  const csv = rows.join('\r\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const date = new Date().toISOString().split('T')[0];
  downloadBlob(blob, `Activity_Log_Export_${date}.csv`);
}

/**
 * Export POA&Ms to CSV.
 */
export function exportPoamsCSV(poams: any[]): void {
  const headers = ['POA&M ID', 'Weakness Name', 'Description', 'System', 'Risk Level', 'Status', 'Days Open', 'Due Date', 'Overdue', 'Assigned To', 'Responsible Party', 'Cost Estimate', 'Milestones', 'Created'];
  const rows: string[] = [headers.map(csvCell).join(',')];

  for (const p of poams) {
    const row = [
      csvCell(p.poam_id),
      csvCell(p.weakness_name),
      csvCell(p.weakness_description),
      csvCell(p.system_name || ''),
      csvCell(p.risk_level),
      csvCell(p.status),
      csvCell(p.days_open),
      csvCell(p.scheduled_completion),
      csvCell(p.is_overdue ? 'Yes' : 'No'),
      csvCell(p.assigned_to_name || ''),
      csvCell(p.responsible_party || ''),
      csvCell(p.cost_estimate || ''),
      csvCell(p.milestone_total > 0 ? `${p.milestone_completed}/${p.milestone_total}` : ''),
      csvCell(p.created_at),
    ];
    rows.push(row.join(','));
  }

  const csv = rows.join('\r\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const date = new Date().toISOString().split('T')[0];
  downloadBlob(blob, `POAMs_Export_${date}.csv`);
}
