/**
 * ForgeComply 360 Reporter - PDF Export Utility
 * Generates professional, print-ready SSP PDF documents
 */

import jsPDF from 'jspdf';
import type { SSPData } from '../types';
import { SECTIONS } from '../config/sections';

// PDF Configuration
const PAGE_WIDTH = 210; // A4 width in mm
const PAGE_HEIGHT = 297; // A4 height in mm
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2);

// Colors
const COLORS = {
  primary: [14, 165, 233] as [number, number, number], // sky-500
  text: [15, 23, 42] as [number, number, number], // slate-900
  textMuted: [100, 116, 139] as [number, number, number], // slate-500
  border: [226, 232, 240] as [number, number, number], // slate-200
  error: [239, 68, 68] as [number, number, number], // red-500
  success: [34, 197, 94] as [number, number, number], // green-500
};

// Impact level colors (for future use)
// const IMPACT_COLORS: Record<string, [number, number, number]> = {
//   Low: [34, 197, 94], // green
//   Moderate: [245, 158, 11], // amber
//   High: [239, 68, 68], // red
// };

interface PDFOptions {
  data: SSPData;
  progress: Record<string, number>;
}

/**
 * Generate SSP PDF document
 */
export async function generatePDF(options: PDFOptions): Promise<Blob> {
  const { data, progress } = options;
  const doc = new jsPDF('p', 'mm', 'a4');

  let currentY = MARGIN;

  // Helper functions
  const addPage = () => {
    doc.addPage();
    currentY = MARGIN;
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (currentY + requiredSpace > PAGE_HEIGHT - MARGIN) {
      addPage();
    }
  };

  const setFont = (style: 'normal' | 'bold' | 'italic' = 'normal', size: number = 10) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
  };

  const addText = (text: string, x: number, y: number, options?: { maxWidth?: number; align?: 'left' | 'center' | 'right' }) => {
    if (options?.maxWidth) {
      const lines = doc.splitTextToSize(text, options.maxWidth);
      doc.text(lines, x, y, { align: options.align || 'left' });
      return lines.length * 5; // Return height used
    }
    doc.text(text, x, y, { align: options?.align || 'left' });
    return 5;
  };

  // ============================================
  // COVER PAGE
  // ============================================
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, PAGE_WIDTH, 60, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  setFont('bold', 28);
  doc.text('System Security Plan', PAGE_WIDTH / 2, 35, { align: 'center' });

  setFont('normal', 12);
  doc.text('FISMA / FedRAMP Authorization Package', PAGE_WIDTH / 2, 48, { align: 'center' });

  // System Info Box
  doc.setTextColor(...COLORS.text);
  currentY = 80;

  // System Name
  setFont('bold', 22);
  const sysName = data.sysName || 'Untitled System';
  doc.text(sysName, PAGE_WIDTH / 2, currentY, { align: 'center' });
  currentY += 12;

  if (data.sysAcronym) {
    setFont('normal', 14);
    doc.setTextColor(...COLORS.textMuted);
    doc.text(`(${data.sysAcronym})`, PAGE_WIDTH / 2, currentY, { align: 'center' });
    currentY += 15;
  }

  // Info Grid
  doc.setTextColor(...COLORS.text);
  currentY += 10;

  const infoItems = [
    ['Owning Agency', data.owningAgency || 'Not specified'],
    ['Authorization Type', data.authType || 'Not specified'],
    ['Impact Level', getOverallImpact(data) || 'Not categorized'],
    ['Control Baseline', data.ctrlBaseline || 'Not selected'],
  ];

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.5);
  doc.rect(MARGIN, currentY - 5, CONTENT_WIDTH, infoItems.length * 12 + 10, 'S');

  infoItems.forEach(([label, value], i) => {
    const y = currentY + (i * 12) + 5;
    setFont('bold', 10);
    doc.text(label + ':', MARGIN + 5, y);
    setFont('normal', 10);
    doc.text(value, MARGIN + 60, y);
  });

  currentY += infoItems.length * 12 + 25;

  // Completion Status
  const overallCompletion = Math.round(
    Object.values(progress).reduce((a, b) => a + b, 0) / Object.keys(progress).length || 0
  );

  setFont('bold', 12);
  doc.text('SSP Completion Status', PAGE_WIDTH / 2, currentY, { align: 'center' });
  currentY += 8;

  // Progress bar
  const barWidth = 100;
  const barX = (PAGE_WIDTH - barWidth) / 2;
  doc.setFillColor(...COLORS.border);
  doc.roundedRect(barX, currentY, barWidth, 8, 4, 4, 'F');
  doc.setFillColor(...COLORS.primary);
  doc.roundedRect(barX, currentY, barWidth * (overallCompletion / 100), 8, 4, 4, 'F');
  currentY += 12;

  setFont('normal', 11);
  doc.setTextColor(...COLORS.primary);
  doc.text(`${overallCompletion}% Complete`, PAGE_WIDTH / 2, currentY, { align: 'center' });

  // Footer
  doc.setTextColor(...COLORS.textMuted);
  setFont('normal', 9);
  doc.text(
    `Generated by ForgeComply 360 Reporter on ${new Date().toLocaleDateString()}`,
    PAGE_WIDTH / 2,
    PAGE_HEIGHT - 20,
    { align: 'center' }
  );

  // ============================================
  // TABLE OF CONTENTS
  // ============================================
  addPage();
  setFont('bold', 18);
  doc.setTextColor(...COLORS.text);
  doc.text('Table of Contents', MARGIN, currentY);
  currentY += 15;

  // Group sections
  const groups: Record<string, typeof SECTIONS> = {};
  SECTIONS.forEach((section) => {
    if (!groups[section.grp]) groups[section.grp] = [];
    groups[section.grp].push(section);
  });

  let pageNum = 3; // Start after cover and TOC
  let sectionNum = 1;

  Object.entries(groups).forEach(([groupName, sections]) => {
    checkPageBreak(20);

    // Group header
    setFont('bold', 11);
    doc.setTextColor(...COLORS.primary);
    doc.text(groupName.toUpperCase(), MARGIN, currentY);
    currentY += 8;

    sections.forEach((section) => {
      checkPageBreak(8);

      setFont('normal', 10);
      doc.setTextColor(...COLORS.text);

      // Section number and title
      doc.text(`${sectionNum}. ${section.label}`, MARGIN + 5, currentY);

      // Completion indicator
      const completion = progress[section.id] || 0;
      const statusColor = completion >= 100 ? COLORS.success : completion > 0 ? COLORS.primary : COLORS.textMuted;
      doc.setTextColor(...statusColor);
      doc.text(`${Math.round(completion)}%`, PAGE_WIDTH - MARGIN - 30, currentY);

      // Page number (dotted line)
      doc.setTextColor(...COLORS.textMuted);
      doc.text(`${pageNum}`, PAGE_WIDTH - MARGIN, currentY, { align: 'right' });

      currentY += 7;
      sectionNum++;
      pageNum++;
    });

    currentY += 5;
  });

  // ============================================
  // SECTION PAGES
  // ============================================
  SECTIONS.forEach((section, idx) => {
    addPage();

    // Section Header
    doc.setFillColor(...COLORS.primary);
    doc.rect(MARGIN, currentY - 5, CONTENT_WIDTH, 15, 'F');

    doc.setTextColor(255, 255, 255);
    setFont('bold', 12);
    doc.text(`${idx + 1}. ${section.label}`, MARGIN + 5, currentY + 5);

    // SSP Reference
    setFont('normal', 9);
    doc.text(section.ref || '', PAGE_WIDTH - MARGIN - 5, currentY + 5, { align: 'right' });

    currentY += 20;

    // Section content based on type
    doc.setTextColor(...COLORS.text);
    renderSectionContent(doc, section.id, data, currentY, checkPageBreak, setFont, addText);
  });

  // Generate blob
  return doc.output('blob');
}

/**
 * Get overall impact level from FIPS 199 categorization
 */
function getOverallImpact(data: SSPData): string {
  const levels = [data.conf, data.integ, data.avail].filter(Boolean);
  if (levels.length === 0) return '';

  if (levels.includes('High')) return 'High';
  if (levels.includes('Moderate')) return 'Moderate';
  return 'Low';
}

/**
 * Render section-specific content
 */
function renderSectionContent(
  doc: jsPDF,
  sectionId: string,
  data: SSPData,
  startY: number,
  checkPageBreak: (space: number) => void,
  setFont: (style: 'normal' | 'bold' | 'italic', size: number) => void,
  _addText: (text: string, x: number, y: number, options?: { maxWidth?: number; align?: 'left' | 'center' | 'right' }) => number
) {
  let y = startY;

  const addField = (label: string, value: string | undefined, _isBold = true) => {
    checkPageBreak(15);
    setFont('bold', 10);
    doc.text(label + ':', MARGIN, y);
    setFont('normal', 10);
    const displayValue = value || 'Not provided';
    const lines = doc.splitTextToSize(displayValue, CONTENT_WIDTH - 50);
    doc.text(lines, MARGIN + 50, y);
    y += Math.max(lines.length * 5, 7);
  };

  const addTextBlock = (label: string, value: string | undefined) => {
    checkPageBreak(25);
    setFont('bold', 10);
    doc.text(label, MARGIN, y);
    y += 6;
    setFont('normal', 10);
    if (value) {
      const lines = doc.splitTextToSize(value, CONTENT_WIDTH);
      doc.text(lines, MARGIN, y);
      y += lines.length * 5 + 5;
    } else {
      doc.setTextColor(...COLORS.textMuted);
      doc.text('Not provided', MARGIN, y);
      doc.setTextColor(...COLORS.text);
      y += 8;
    }
  };

  switch (sectionId) {
    case 'system_info':
      addField('System Name', data.sysName);
      addField('System Acronym', data.sysAcronym);
      addField('FISMA ID', data.fismaId);
      addField('FedRAMP ID', data.fedrampId);
      addField('Owning Agency', data.owningAgency);
      addField('Agency Component', data.agencyComp);
      addField('Cloud Model', data.cloudModel);
      addField('Deployment Model', data.deployModel);
      addField('Authorization Type', data.authType);
      addField('Operational Date', data.opDate);
      addTextBlock('System Description', data.sysDesc);
      break;

    case 'fips_199':
      addField('Confidentiality', data.conf);
      addField('Integrity', data.integ);
      addField('Availability', data.avail);
      addField('Overall Impact Level', getOverallImpact(data));
      addTextBlock('Categorization Justification', data.catJust);
      break;

    case 'control_baseline':
      addField('Selected Baseline', data.ctrlBaseline);
      addField('Tailoring Applied', data.tailoring);
      addTextBlock('Baseline Justification', data.baseJust);
      break;

    case 'rmf_lifecycle':
      addField('Current RMF Step', data.rmfCurrentStep);
      addField('Target ATO Date', data.rmfTargetAto);
      break;

    case 'authorization_boundary':
      addTextBlock('Boundary Narrative', data.bndNarr);
      break;

    case 'data_flow':
      addTextBlock('Data Flow Narrative', data.dfNarr);
      addField('Encryption at Rest', data.encRest);
      addField('Encryption in Transit', data.encTransit);
      addField('Key Management', data.keyMgmt);
      addField('Data Disposal', data.dataDisposal);
      break;

    case 'network_architecture':
      addTextBlock('Network Narrative', data.netNarr);
      addField('Primary Data Center', data.primaryDC);
      addField('Secondary/DR Data Center', data.secondaryDC);
      break;

    case 'personnel':
      addField('System Owner', data.soName);
      addField('SO Email', data.soEmail);
      addField('Authorizing Official', data.aoName);
      addField('AO Email', data.aoEmail);
      addField('ISSO', data.issoName);
      addField('ISSO Email', data.issoEmail);
      addField('ISSM', data.issmName);
      addField('ISSM Email', data.issmEmail);
      addField('SCA', data.scaName);
      addField('SCA Email', data.scaEmail);
      addField('Privacy Officer', data.poName);
      addField('PO Email', data.poEmail);
      break;

    case 'digital_identity':
      addField('Identity Assurance Level (IAL)', data.ial);
      addField('Authenticator Assurance Level (AAL)', data.aal);
      addField('Federation Assurance Level (FAL)', data.fal);
      addField('MFA Methods', data.mfaMethods);
      addTextBlock('Identity Narrative', data.idNarr);
      break;

    case 'separation_of_duties':
      addField('Dual Control Requirements', data.dualControl);
      addField('Privileged Access Management', data.privAccess);
      break;

    case 'privacy_analysis':
      addField('System Collects PII?', data.ptaCollectsPii);
      addField('PII Types', data.ptaPiiTypes);
      addField('Approximate Record Count', data.ptaRecordCount);
      addField('PIA Required?', data.ptaPiaRequired);
      addField('SORN Status', data.sornStatus);
      addField('SORN Number', data.sornNumber);
      break;

    case 'contingency_plan':
      addTextBlock('CP Purpose', data.cpPurpose);
      addTextBlock('CP Scope', data.cpScope);
      addField('Recovery Time Objective (RTO)', data.rto);
      addField('Recovery Point Objective (RPO)', data.rpo);
      addField('Maximum Tolerable Downtime', data.mtd);
      addField('Backup Frequency', data.backupFreq);
      addField('Last CP Test Date', data.cpTestDate);
      addField('CP Test Type', data.cpTestType);
      break;

    case 'incident_response':
      addTextBlock('IR Purpose', data.irPurpose);
      addTextBlock('IR Scope', data.irScope);
      addField('US-CERT Notification Time', data.certTime);
      addField('Last IR Test Date', data.irTestDate);
      break;

    case 'config_management':
      addTextBlock('CM Purpose', data.cmPurpose);
      addTextBlock('Change Control Process', data.cmChangeNarr);
      break;

    case 'continuous_monitoring':
      addField('ISCM Strategy Type', data.iscmType);
      addField('Control Assessment Rotation', data.ctrlRotation);
      addTextBlock('ISCM Narrative', data.iscmNarrative);
      addField('Significant Change Criteria', data.sigChangeCriteria);
      addField('ATO Expiry Date', data.atoExpiry);
      addField('Next Assessment Date', data.nextAssessment);
      break;

    case 'poam':
      addField('Review Frequency', data.poamFreq);
      addTextBlock('Remediation Workflow', data.poamWf);
      break;

    default:
      setFont('italic', 10);
      doc.setTextColor(...COLORS.textMuted);
      doc.text('Section content not available for PDF export.', MARGIN, y);
      break;
  }
}

/**
 * Download PDF to user's device
 */
export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
